variables:
    JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia"

.test_template: &test_definition
  script:
    - mkdir -p "$CI_PROJECT_DIR/.julia" && ls -al "$CI_PROJECT_DIR/.julia"
    - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("KM3io"); Pkg.test("KM3io"; coverage = true)'
    - julia -e 'using Pkg; Pkg.add("Coverage"); 
      import KM3io; cd(joinpath(dirname(pathof(KM3io)), ".."));
      using Coverage; cl, tl = get_summary(process_folder());
      println("(", cl/tl*100, "%) covered")'
    - ls -al "$CI_PROJECT_DIR/.julia"

cache:
  paths:
    - "$CI_PROJECT_DIR/.julia"
  key: "$CI_COMMIT_REF_SLUG"

test:julia-1.0:
  image: julia:1.0
  <<: *test_definition

test:julia-1.1:
  image: julia:1.1
  <<: *test_definition

test:julia-1.2:
  image: julia:1.2
  <<: *test_definition

test:julia-1.3:
  image: julia:1.3
  <<: *test_definition

pages:
  image: julia:1.3
  stage: deploy
  script:
    - julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
    - mkdir -p public
    - mv docs/build public/dev
  artifacts:
    paths:
      - public
  only:
    - master
