"""
# KM3NeT Data Definitions v3.1.0-7-gab56b85
https://git.km3net.de/common/km3net-dataformat
"""

module ROOT
  const TTREE_ONLINE_TIMESLICE =     "KM3NET_TIMESLICE"   
  const TTREE_ONLINE_TIMESLICEL0 =   "KM3NET_TIMESLICE_L0"
  const TTREE_ONLINE_TIMESLICEL1 =   "KM3NET_TIMESLICE_L1"
  const TTREE_ONLINE_TIMESLICEL2 =   "KM3NET_TIMESLICE_L2"
  const TTREE_ONLINE_TIMESLICESN =   "KM3NET_TIMESLICE_SN"
  const TTREE_ONLINE_SUMMARYSLICE =  "KM3NET_SUMMARYSLICE"
  const TTREE_ONLINE_EVENT =         "KM3NET_EVENT"       
  const TTREE_OFFLINE_EVENT =        "E"                  
  const TBRANCH_ONLINE_TIMESLICE =     "KM3NET_TIMESLICE"   
  const TBRANCH_ONLINE_TIMESLICEL0 =   "km3net_timeslice_L0"
  const TBRANCH_ONLINE_TIMESLICEL1 =   "km3net_timeslice_L1"
  const TBRANCH_ONLINE_TIMESLICEL2 =   "km3net_timeslice_L2"
  const TBRANCH_ONLINE_TIMESLICESN =   "km3net_timeslice_SN"
  const TBRANCH_ONLINE_SUMMARYSLICE =  "KM3NET_SUMMARYSLICE"
  const TBRANCH_ONLINE_EVENT =         "KM3NET_EVENT"       
  const TBRANCH_OFFLINE_EVENT =        "Evt"                
  const COMPRESSION_LEVEL_ONLINE_TIMESLICE =     0
  const COMPRESSION_LEVEL_ONLINE_TIMESLICEL0 =   0
  const COMPRESSION_LEVEL_ONLINE_TIMESLICEL1 =   2
  const COMPRESSION_LEVEL_ONLINE_TIMESLICEL2 =   2
  const COMPRESSION_LEVEL_ONLINE_TIMESLICESN =   2
  const COMPRESSION_LEVEL_ONLINE_SUMMARYSLICE =  1
  const COMPRESSION_LEVEL_ONLINE_EVENT =         0
  const COMPRESSION_LEVEL_OFFLINE_EVENT =        1
  const BASKET_SIZE_ONLINE_TIMESLICE =       5000000
  const BASKET_SIZE_ONLINE_TIMESLICEL0 =   500000000
  const BASKET_SIZE_ONLINE_TIMESLICEL1 =     5000000
  const BASKET_SIZE_ONLINE_TIMESLICEL2 =     5000000
  const BASKET_SIZE_ONLINE_TIMESLICESN =     5000000
  const BASKET_SIZE_ONLINE_SUMMARYSLICE =    5000000
  const BASKET_SIZE_ONLINE_EVENT =           5000000
  const BASKET_SIZE_OFFLINE_EVENT =          5000000
  const SPLIT_LEVEL_ONLINE_TIMESLICE =     1
  const SPLIT_LEVEL_ONLINE_TIMESLICEL0 =   2
  const SPLIT_LEVEL_ONLINE_TIMESLICEL1 =   2
  const SPLIT_LEVEL_ONLINE_TIMESLICEL2 =   2
  const SPLIT_LEVEL_ONLINE_TIMESLICESN =   2
  const SPLIT_LEVEL_ONLINE_SUMMARYSLICE =  1
  const SPLIT_LEVEL_ONLINE_EVENT =         1
  const SPLIT_LEVEL_OFFLINE_EVENT =        4
end
