"""
# KM3NeT Data Definitions v3.6.0
https://git.km3net.de/common/km3net-dataformat
"""

module W2LIST_GSEAGEN
  const W2LIST_GSEAGEN_PS = 0
  const W2LIST_GSEAGEN_EG = 1
  const W2LIST_GSEAGEN_XSEC_MEAN = 2
  const W2LIST_GSEAGEN_COLUMN_DEPTH = 3
  const W2LIST_GSEAGEN_P_EARTH = 4
  const W2LIST_GSEAGEN_WATER_INT_LEN = 5
  const W2LIST_GSEAGEN_P_SCALE = 6
  const W2LIST_GSEAGEN_BX = 7
  const W2LIST_GSEAGEN_BY = 8
  const W2LIST_GSEAGEN_ICHAN = 9
  const W2LIST_GSEAGEN_CC = 10
  const W2LIST_GSEAGEN_DISTAMAX = 11
  const W2LIST_GSEAGEN_WATERXSEC = 12
  const W2LIST_GSEAGEN_XSEC = 13
  const W2LIST_GSEAGEN_DXSEC = 14
  const W2LIST_GSEAGEN_TARGETA = 15
  const W2LIST_GSEAGEN_TARGETZ = 16
  const W2LIST_GSEAGEN_VERINCAN = 17
  const W2LIST_GSEAGEN_LEPINCAN = 18
  const W2LIST_GSEAGEN_N_RETRIES = 19
  const W2LIST_GSEAGEN_CUSTOM_YAW = 20
  const W2LIST_GSEAGEN_CUSTOM_PITCH = 21
  const W2LIST_GSEAGEN_CUSTOM_ROLL = 22
end
