"""
# KM3NeT Data Definitions v3.6.0
https://git.km3net.de/common/km3net-dataformat
"""

module W2LIST_KM3BUU
  const W2LIST_KM3BUU_PS = 0
  const W2LIST_KM3BUU_EG = 1
  const W2LIST_KM3BUU_XSEC_MEAN = 2
  const W2LIST_KM3BUU_COLUMN_DEPTH = 3
  const W2LIST_KM3BUU_P_EARTH = 4
  const W2LIST_KM3BUU_WATER_INT_LEN = 5
  const W2LIST_KM3BUU_BX = 7
  const W2LIST_KM3BUU_BY = 8
  const W2LIST_KM3BUU_ICHAN = 9
  const W2LIST_KM3BUU_CC = 10
  const W2LIST_KM3BUU_XSEC = 13
  const W2LIST_KM3BUU_DXSEC = 14
  const W2LIST_KM3BUU_TARGETA = 15
  const W2LIST_KM3BUU_TARGETZ = 16
  const W2LIST_KM3BUU_VERINCAN = 17
  const W2LIST_KM3BUU_LEPINCAN = 18
  const W2LIST_KM3BUU_GIBUU_WEIGHT = 23
  const W2LIST_KM3BUU_GIBUU_SCAT_TYPE = 24
  const W2LIST_KM3BUU_LEPPROP_SAMPLES = 25
end
